import type { Metadata } from 'next'
import "./globals.css";
import { Cairo } from "next/font/google";

// components
import Navbar from "./components/Navbar";
import { ThemeProvider } from "./context/ThemeContext";

const rubik = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
          <Navbar />
        <body dir="rtl" className={rubik.className}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
